spring:
  jpa:
    hibernate:
      ddl-auto: update  # Use 'update' for first deployment, then change to 'validate'
    show-sql: false
  h2:
    console:
      enabled: false
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

logging:
  level:
    com.kousen.cert: INFO
    org.springframework.security: WARN
    org.hibernate: WARN